/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.apache.pdfbox.pdfbox)
    api(libs.technology.tabula.tabula)
    api(libs.org.apache.poi.poi.ooxml)
}

group = "prototype"
version = "1.0"
description = "pdf-to-excel"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
